// @includepath "~/Documents/;%USERPROFILE%Documents";
// @include "basiljs/basil.js";

function draw() {

b.clear(b.doc());
b.units(b.MM);

var honorifics = [
    "Admiral",
    "Air Cdre",
    "Air Marshal",
    "Alderman",
    "Ambassador",
    "Archbishop",
    "Archdeacon",
    "Baron of Lewes",
    "Baron",
    "Baroness",
    "Bishop",
    "Brigadier",
    "Brother",
    "Buergermeister",
    "Canon",
    "Captain",
    "Catholic Chaplain",
    "Chairman",
    "Chevalier",
    "Chief Constable",
    "Chief Fire Officer",
    "Chief Inspector",
    "Chief Rabbi Sir",
    "Chief Supt",
    "Chief",
    "Colonel Dr",
    "Colonel",
    "Commander",
    "Commodore",
    "Comte",
    "Consort to the Deputy Mayor of Wirral",
    "Consul",
    "Councillor Mrs",
    "Councillor",
    "Count",
    "Countess",
    "Dame",
    "Dato'",
    "Datuk",
    "Dean",
    "Deputy Mayor of Sefton Councillor",
    "Deputy Vice-Chancellor Professor",
    "District Attorney",
    "District Judge",
    "Doctor",
    "Dott.",
    "Dr",
    "Duchess",
    "Duke",
    "Earl",
    "Emeritus Professor",
    "Eng",
    "Eur Ing",
    "Father",
    "Fiona",
    "Flt Lt",
    "Frau",
    "Frú",
    "General",
    "Governor",
    "Group Captain",
    "Her Excellency",
    "Her Honour Judge",
    "Her Honour",
    "Her Royal Highness Princess",
    "Her Royal Highness",
    "Herr",
    "High Sheriff of Merseyside",
    "His Excellency Chief",
    "His Excellency",
    "His Grace the Duke of Westminster",
    "His Grace The Duke",
    "His Grace",
    "His Honour Judge",
    "His Honour",
    "His Royal Highness Prince",
    "His Royal Highness",
    "Hon. Lord",
    "Hon",
    "Honourable",
    "HRH Princess",
    "Ing",
    "Judge",
    "Justice",
    "Lady Mayoress",
    "Lady",
    "Lieutenant Colonel",
    "Lieutenant Commander",
    "Lieutenant",
    "Lord Lieutenant of Merseyside Dame",
    "Lord Lieutenant of Merseyside Dr",
    "Lord Lieutenant",
    "Lord Mayor",
    "Lord",
    "Lt Cdr",
    "Lt Colonel",
    "Madam",
    "Mademoiselle",
    "Major",
    "Majors",
    "Mar",
    "Marchioness",
    "Master",
    "Mayor",
    "Mayoress",
    "Messrs",
    "Methodist Chaplain",
    "Miss",
    "Mme",
    "Monsieur",
    "Monsignor",
    "Mr and Mrs",
    "Mr Justice",
    "Mr",
    "Mrs",
    "Ms",
    "Mx",
    "of Birkenhead",
    "of Quarry Bank",
    "Pastor",
    "Police Constable",
    "Pr Eng",
    "Prebendary",
    "President",
    "Prince",
    "Princess",
    "Pro-Vice-Chancellor Professor",
    "Pro-Vice-Chancellor",
    "Professor Dame",
    "Professor Lord",
    "Professor Sir",
    "Professor the Lord",
    "Professor",
    "QPM",
    "Rabbi",
    "Revd. Cannon Dr.",
    "Reverend Brother",
    "Reverend Canon",
    "Reverend Dr",
    "Reverend Father",
    "Reverend Professor",
    "Reverend Sister",
    "Reverend",
    "Right Reverend",
    "Rt Hon",
    "Rt. Hon. Dame",
    "Rt. Hon. Lord Justice",
    "Rt. Hon. Sir",
    "Senator",
    "Senior Executive Assistant",
    "Sergent",
    "Sheikh",
    "Sir",
    "Sister",
    "Squadron Leader",
    "Sub Lt",
    "The Countess of",
    "The Duke of",
    "The Earl of",
    "The Editor",
    "The High Sheriff of Merseyside Dr.",
    "The High Sheriff",
    "The Hon Dame",
    "The Hon. Dr.",
    "The Hon. Mr. Justice",
    "The Hon. Mr",
    "The Honorable Dame",
    "The Honorable Mrs",
    "The Honorable Sir",
    "The Honorable",
    "The Lord",
    "The Mayor-Elec of Wirral Councillor",
    "The Mayor",
    "The Most Rev",
    "The Right Hon. Lord Justice",
    "The Right Hon. the Lord",
    "The Right Honourable",
    "The Rt Hon Lady Justice",
    "The Rt Hon Lord",
    "The Rt Hon Mrs",
    "The Rt Hon the Lady",
    "The Rt Hon the Lord",
    "The Rt Hon",
    "The Rt Honourable Earl of",
    "The Rt Rev Bishop",
    "The Rt Rev Dr",
    "The Rt Rev",
    "The Rt. Hon the Lord",
    "The Rt. Hon. Dame",
    "The Rt. Hon. Lady Justice",
    "The Rt. Hon. Lord",
    "The Rt. Hon. The Baroness",
    "The Rt. Hon. the Earl of",
    "The Rt. Hon. The Lady",
    "The Rt. Hon. The Lord",
    "The Rt. Hon.",
    "The Rt. Hon",
    "The Rt. Rev. Dr.",
    "The Rt. Revd. Dr.",
    "The Rt. Worshipful",
    "The Rt. Worshipfull",
    "The Very Revd. Dr.",
    "The Very Reverend",
    "The Worship the Mayor of Wirral",
    "The Worship the Mayor",
    "The Worshipful the Lord Mayor of Liverpool",
    "The Worshipful the Lord Mayor",
    "The Worshipful the Mayor of Halton",
    "The Worshipful the Mayor of Knowsley",
    "The Worshipful the Mayor of Sefton",
    "The Worshipful the Mayor of St. Helens",
    "The Worshipful the Mayor of",
    "The Worshipful the Mayor",
    "Venerable",
    "Very Reverend",
    "Vice Admiral Sir",
    "Vice-Chancellor Professor",
    "Vice-Chancellor",
    "Viscount",
    "Viscountess",
    "Wing Commander"
  ]

var famousPeople = [
        "Aage Bohr",
        "Abdul Qadeer Khan",
        "Abu Nasr Al-Farabi",
        "Ada Lovelace",
        "Adalbert Czerny",
        "Agnes Arber",
        "Ahmed Zewail",
        "Al-Battani",
        "Alan Turing",
        "Albert Abraham Michelson",
        "Albert Einstein",
        "Alberto Santos-Dumont",
        "Albrecht von Haller",
        "Aldo Leopold",
        "Alessandro Volta",
        "Alexander Bain",
        "Alexander Brongniart",
        "Alexander Fleming",
        "Alexander Graham Bell",
        "Alexander Von Humboldt",
        "Alfred Binet",
        "Alfred Blalock",
        "Alfred Kinsey",
        "Alfred Nobel",
        "Alfred Russel Wallace",
        "Alfred Wegener",
        "Amedeo Avogadro",
        "Anders Celsius",
        "Andre Marie Ampère",
        "Andreas Vesalius",
        "Angel Alcala",
        "Antoine Lavoisier",
        "Antonie van Leeuwenhoek",
        "Antonio Meucci",
        "Antony Hewish",
        "Archimedes",
        "Aristarchus",
        "Aristotle",
        "Arnold Orville Beckman",
        "Arnold Sommerfeld",
        "Arthur Eddington",
        "Artturi Virtanen",
        "Avicenna",
        "B. F. Skinner",
        "Barbara McClintock",
        "Beatrix Potter",
        "Benjamin Cabrera",
        "Benjamin Franklin",
        "Benjamin Thompson",
        "Bernardo Houssay",
        "Bill Nye",
        "Blaise Pascal",
        "Brahmagupta",
        "Brian Cox",
        "C. V. Raman",
        "Carl Bosch",
        "Carl Friedrich Gauss",
        "Carl Sagan",
        "Carolus Linnaeus",
        "Charles Babbage",
        "Charles Darwin",
        "Charles Lyell",
        "Charles Sherrington",
        "Charles-Augustin de Coulomb",
        "Chen-Ning Yang",
        "Christiaan Huygens",
        "Christiane Nusslein-Volhard",
        "Clarence Birdseye",
        "Claude Bernard",
        "Claude Levi-Strauss",
        "Clyde Tombaugh",
        "Daniel Bernoulli",
        "David Bohm",
        "David Hilbert",
        "Dian Fossey",
        "Dmitri Mendeleev",
        "Dorothy Hodgkin",
        "E. O. Wilson",
        "Edmund Halley",
        "Edward Jenner",
        "Edward Teller",
        "Edwin Herbert Land",
        "Edwin Hubble",
        "Elizabeth Blackwell",
        "Emil Adolf Behring",
        "Emil Fischer",
        "Emil Kraepelin",
        "Emile Berliner",
        "Enrico Fermi",
        "Eratosthenes",
        "Ernest Rutherford",
        "Ernesto Illy",
        "Ernst Haeckel",
        "Ernst Ising",
        "Ernst Mach",
        "Ernst Mayr",
        "Ernst Werner von Siemens",
        "Erwin Chargaff",
        "Erwin Schrödinger",
        "Euclid",
        "Evangelista Torricelli",
        "Francesco Redi",
        "Francis Bacon",
        "Francis Crick",
        "Francis Galton",
        "Frank Hornby",
        "Franz Boas",
        "Frederick Gowland Hopkins",
        "Frederick Sanger",
        "Frederick Soddy",
        "Friedrich August Kekulé",
        "Friedrich Wöhler",
        "Fritz Haber",
        "Galen",
        "Galileo Galilei",
        "Gene Shoemaker",
        "Georg Ohm",
        "George Beadle",
        "George Gamow",
        "George Gaylord Simpson",
        "George Washington Carver",
        "Georges-Louis Leclerc, Comte de Buffon",
        "Gertrude Elion",
        "Gerty Theresa Cori",
        "Glenn Seaborg",
        "Gottfried Leibniz",
        "Gottlieb Daimler",
        "Grace Murray Hopper",
        "Gregor Mendel",
        "Guglielmo Marconi",
        "Gustav Kirchoff",
        "Gustav Ludwig Hertz",
        "Hans Bethe",
        "Hans Christian Oersted",
        "Hans Selye",
        "Harriet Quimby",
        "Hedy Lamarr",
        "Heike Kamerlingh Onnes",
        "Heinrich Hertz",
        "Hendrik Antoon Lorentz",
        "Henri Becquerel",
        "Henrietta Swan Leavitt",
        "Henry Bessemer",
        "Henry Cavendish",
        "Henry David Thoreau",
        "Henry Ford",
        "Henry Moseley",
        "Hermann Rorschach",
        "Hermann von Helmholtz",
        "Homi Jehangir Bhabha",
        "Humphry Davy",
        "Ibn Battuta",
        "Ibn Rushd",
        "Inge Lehmann",
        "Irene Joliot-Curie",
        "Isaac Newton",
        "Ivan Pavlov",
        "J. Hans D. Jensen",
        "J. J. Thomson",
        "J. Robert Oppenheimer",
        "Jagadish Chandra Bose",
        "James Chadwick",
        "James Clerk Maxwell",
        "James Dwight Dana",
        "James Hutton",
        "James Prescott Joule",
        "James Watson",
        "James Watt",
        "Jan Baptist von Helmont",
        "Jane Goodall",
        "Jane Marcet",
        "Jean Andre Deluc",
        "Jean Piaget",
        "Jean-Baptiste Lamarck",
        "Jim Al-Khalili",
        "Jocelyn Bell Burnell",
        "Johannes Kepler",
        "John Archibald Wheeler",
        "John Bardeen",
        "John Dalton",
        "John Locke",
        "John Logie Baird",
        "John Napier",
        "John Needham",
        "John Ray",
        "John von Neumann",
        "Jonas Salk",
        "Joseph Banks",
        "Joseph Lister",
        "Joseph Priestley",
        "Justus von Liebig",
        "K. Eric Drexler",
        "Karl F. Herzfeld",
        "Karl Landsteiner",
        "Katharine Burr Blodgett",
        "Keisuke Ito",
        "Kip S. Thorne",
        "Konrad Lorenz",
        "Kristian Birkeland",
        "Lee De Forest",
        "Leland Clark",
        "Leo Szilard",
        "Leon Foucault",
        "Leonardo da Vinci",
        "Leonhard Euler",
        "Lester R. Brown",
        "Linus Pauling",
        "Lise Meitner",
        "Louis Agassiz",
        "Louis de Broglie",
        "Louis Pasteur",
        "Lucretius",
        "Ludwig Boltzmann",
        "Luigi Galvani",
        "Luis Alvarez",
        "Luther Burbank",
        "Lynn Margulis",
        "Mae Carol Jemison",
        "Marcello Malpighi",
        "Marguerite Perey",
        "Maria Gaetana Agnesi",
        "Maria Goeppert-Mayer",
        "Maria Mitchell",
        "Marie Curie",
        "Mario Molina",
        "Mary Anning",
        "Max Born",
        "Max Delbruck",
        "Max Planck",
        "Max von Laue",
        "Michael E. Brown",
        "Michael Faraday",
        "Michio Kaku",
        "Mihailo Petrovic Alas",
        "Mohammad Abdus Salam",
        "Muhammad ibn Musa al-Khwarizmi",
        "Murray Gell-Mann",
        "Neil deGrasse Tyson",
        "Niccolo Leoniceno",
        "Nicholas Culpeper",
        "Nicolaus Copernicus",
        "Niels Bohr",
        "Nikola Tesla",
        "Noam Chomsky",
        "Omar Khayyam",
        "Otto Hahn",
        "Otto Haxel",
        "Paul Dirac",
        "Paul Ehrlich",
        "Pearl Kendrick",
        "Percy Lavon Julian",
        "Peter Debye",
        "Pierre Curie",
        "Pierre de Fermat",
        "Pierre-Simon Laplace",
        "Prafulla Chandra Ray",
        "Prokop Divis",
        "Pythagoras",
        "Rachel Carson",
        "Ramon Barba",
        "Randy Pausch",
        "René Descartes",
        "Richard Feynman",
        "Rita Levi-Montalcini",
        "Robert Bosch",
        "Robert Boyle",
        "Robert Brown",
        "Robert Bunsen",
        "Robert Goddard",
        "Robert Hooke",
        "Robert Koch",
        "Ronald Ross",
        "Rosalind Franklin",
        "Rudolf Christian Karl Diesel",
        "Rudolf Virchow",
        "Salim Ali",
        "Sally Ride",
        "Santiago Ramon y Cajal",
        "Sergei Winogradsky",
        "Sheldon Lee Glashow",
        "Shintaro Hirase",
        "Sigmund Freud",
        "Srinivasa Ramanujan",
        "Stephanie Kwolek",
        "Stephen Hawking",
        "Steven Chu",
        "Subrahmanyan Chandrasekhar",
        "Svante Arrhenius",
        "Sven Wingqvist",
        "Thabit ibn Qurra",
        "Thales of Miletus",
        "Theodor Schwann",
        "Theodosius Dobzhansky",
        "Thomas Alva Edison",
        "Thomas Burnet",
        "Thomas Hunt Morgan",
        "Thomas Kuhn",
        "Thomas Midgeley Jr.",
        "Thomas Newcomen",
        "Thomas Willis",
        "Tim Noakes",
        "Timothy John Berners-Lee",
        "Trofim Lysenko",
        "Tycho Brahe",
        "Ukichiro Nakaya",
        "Virginia Apgar",
        "Vladimir Vernadsky",
        "Walter Schottky",
        "Walther Wilhelm Georg Bothe",
        "Werner Heisenberg",
        "Wernher Von Braun",
        "Wilbur and Orville Wright",
        "Wilhelm Ostwald",
        "Wilhelm Röntgen",
        "Wilhelm Wundt",
        "Willard Frank Libby",
        "Willard Gibbs",
        "William Bayliss",
        "William Buckland",
        "William Harvey",
        "William Herschel",
        "William Hopkins",
        "William John Swainson",
        "William Ramsay",
        "William Smith",
        "William Thomson",
        "Wolfgang Ernst Pauli",
        "Zora Neale Hurston"
    ]

    var bodyParts = [
    "ankle",
    "arm",
    "back",
    "belly",
    "bottom",
    "breast",
    "buttocks",
    "calf",
    "cheek",
    "chin",
    "ear",
    "elbow",
    "eye",
    "eyebrow",
    "eyelash",
    "finger",
    "fist",
    "foot",
    "forearm",
    "forehead",
    "hair",
    "hand",
    "head",
    "hip",
    "knee",
    "leg",
    "lip",
    "lower leg",
    "mouth",
    "neck",
    "nose",
    "nostril",
    "shoulder",
    "thigh",
    "thumb",
    "toe",
    "tongue",
    "tooth",
    "upper arm",
    "waist",
    "wrist"
  ]

  var tolkienCharacter = [
    "Ælfwine",
    "Éomer",
    "Éomund",
    "Éothéod",
    "Éothain",
    "Éowyn",
    "Írildë",
    "Adalgrim Took",
    "Adanedhel",
    "Adanel",
    "Adrahil II",
    "Adrahil",
    "Aegnor",
    "Aerin",
    "Agarwaen",
    "Aikanáro",
    "Aiwendil",
    "Alatáriel",
    "Alatar",
    "Aldamir",
    "Aldaron",
    "Aldor",
    "Amandil",
    "Amdír",
    "Amlaith",
    "Amras",
    "Amrod",
    "Amroth",
    "Amrothos",
    "Anárion",
    "Anairë",
    "Anardil",
    "Anborn",
    "Ancalagon",
    "Andróg",
    "Andrast",
    "Andreth",
    "Anfauglir",
    "Angbor",
    "Angrod",
    "Annatar",
    "Ar Abattârik",
    "Ar Adûnakhôr",
    "Ar Gimilzôr",
    "Ar Inziladûn",
    "Ar Pharazôn",
    "Ar Sakalthôr",
    "Ar Zimraphel",
    "Ar- Zimrathôn",
    "Arador",
    "Araglas",
    "Aragorn I",
    "Aragorn II",
    "Aragost",
    "Arahad I",
    "Arahad II",
    "Arahael",
    "Aranarth",
    "Arantar",
    "Aranuir",
    "Araphant",
    "Araphor",
    "Arassuil",
    "Aratan",
    "Aratar",
    "Arathorn I",
    "Arathorn II",
    "Araval",
    "Aravir",
    "Aravorn",
    "Aredhel",
    "Argeleb I",
    "Argeleb II",
    "Argon",
    "Argonui",
    "Arien",
    "Aros",
    "Arthedain",
    "Arvedui",
    "Arvegil",
    "Arveleg I",
    "Arveleg II",
    "Arwen",
    "Asfaloth",
    "Atanatar I",
    "Atanatar II",
    "Aulë",
    "Ausir",
    "Avranc",
    "Azaghâl",
    "Azog",
    "Bëor",
    "Bór",
    "Balbo Baggins",
    "Baldor",
    "Balin",
    "Baragund",
    "Barahir (Steward)",
    "Barahir",
    "Baran",
    "Bard the Bowman",
    "Barliman Butterbur",
    "Bauglir",
    "Belecthor I",
    "Belecthor II",
    "Beleg of Arnor",
    "Beleg",
    "Belegorn",
    "Belegund",
    "Belemir",
    "Belladonna Took",
    "Beorn",
    "Berúthiel",
    "Bereg",
    "Beregond (Steward)",
    "Beregond",
    "Beren (Steward)",
    "Beren",
    "Bergil",
    "Bert",
    "Berylla Boffin",
    "Bifur",
    "Bilbo Baggins",
    "Bill Ferny",
    "Bill the Pony",
    "Bill the Troll",
    "Bofur",
    "Boldog",
    "Bolg",
    "Bombur",
    "Borin",
    "Boromir (Steward)",
    "Boromir",
    "Boron",
    "Borondir",
    "Brand II",
    "Brand",
    "Brandir",
    "Brego",
    "Bregolas",
    "Bregor",
    "Brodda",
    "Brytta Léofa",
    "Bucca of the Marish",
    "Bullroarer Took",
    "Bungo Baggins",
    "Círdan",
    "Calembel",
    "Calimehtar",
    "Calmacil",
    "Captain of the Haven",
    "Caranthir",
    "Carcharoth",
    "Castamir the Usurper",
    "Celeborn",
    "Celebrían",
    "Celebrimbor",
    "Celebrindor",
    "Celegorm",
    "Celepharn",
    "Cemendur",
    "Ceorl",
    "Cirion",
    "Ciryaher",
    "Ciryandil",
    "Ciryon",
    "Curufin",
    "Curunír",
    "Dáin I",
    "Dáin II Ironfoot",
    "Déagol",
    "Déor",
    "Dís (Middle-earth)",
    "Daeron",
    "Daughters of Finwë",
    "Deórwine",
    "Denethor (First Age)",
    "Denethor I",
    "Denethor II",
    "Dernhelm",
    "Diamond of Long Cleeve",
    "Dior (Steward)",
    "Dior",
    "Dori",
    "Dorlas",
    "Draugluin",
    "Duilin",
    "Durin II",
    "Durin III",
    "Durin IV",
    "Durin V",
    "Durin VI",
    "Durin VII",
    "Durin",
    "Durin's Bane",
    "Dwalin",
    "Eärendil of Gondor",
    "Eärendil",
    "Eärendur of Andúnië",
    "Eärendur of Arnor",
    "Eärendur son of Tar-Amandil",
    "Eärnil I",
    "Eärnil II",
    "Eärnur",
    "Eärwen",
    "Eöl",
    "Eönwë",
    "Ecthelion I",
    "Ecthelion II",
    "Ecthelion of the Fountain",
    "Egalmoth",
    "Eilinel",
    "Elanor the Fair",
    "Elbereth",
    "Eldacar of Arnor",
    "Eldacar of Gondor",
    "Eldarion",
    "Elemmakil",
    "Elendil",
    "Elendor",
    "Elendur of Arnor",
    "Elendur son of Isildur",
    "Elenna",
    "Elenwë",
    "Elessar",
    "Elfhelm",
    "Elfhild",
    "Elfwine",
    "Elladan",
    "Elmo",
    "Elrohir",
    "Elrond",
    "Elros",
    "Elu",
    "Eluréd and Elurín",
    "Elven-king",
    "Elwë",
    "Elwing",
    "Emeldir",
    "Emerië",
    "Enel",
    "Enelyë",
    "Eorl the Young",
    "Eradan",
    "Erendis",
    "Erestor",
    "Erkenbrand",
    "Eru Ilúvatar",
    "Estë",
    "Estel",
    "Estelmo",
    "Fëanor",
    "Fíli",
    "Fíriel",
    "Faniel",
    "Faramir Took",
    "Faramir",
    "Farmer Maggot",
    "Fastred of Greenholm",
    "Felaróf",
    "Female hobbits",
    "Fengel",
    "Ferumbras III Took",
    "Finarfin",
    "Findis",
    "Finduilas of Dol Amroth",
    "Finduilas",
    "Fingolfin",
    "Fingon",
    "Finrod Felagund",
    "Finvain",
    "Finwë",
    "Folcwine",
    "Forlong the Fat",
    "Fortinbras II Took",
    "Fréa",
    "Fréaláf Hildeson",
    "Fréawine",
    "Frór",
    "Freca",
    "Fredegar (Fatty) Bolger",
    "Frerin",
    "Frodo Baggins",
    "Fuinur",
    "Fundin",
    "Galador",
    "Galadriel",
    "Galdor of Gondolin",
    "Galdor of the Havens",
    "Galdor the Tall",
    "Gamil Zirak",
    "Gamling",
    "Gandalf",
    "Gerontius Took",
    "Ghân-buri-Ghân",
    "Gil-galad",
    "Gildor Inglorion",
    "Gilrain",
    "Gimilkhâd",
    "Gimli",
    "Ginglith",
    "Girion",
    "Glóin",
    "Glóredhel",
    "Glanhír",
    "Glaurung",
    "Glorfindel",
    "Goldberry",
    "Goldwine",
    "Golfimbul",
    "Gollum",
    "Gorbag",
    "Gorlim",
    "Gormadoc Brandybuck",
    "Gorthaur",
    "Gothmog (First Age)",
    "Gothmog (Third Age)",
    "Gríma",
    "Grór",
    "Gram",
    "Grimbold",
    "Grishnákh",
    "Gwaihir",
    "Gwathir",
    "Gwindor",
    "Háma",
    "Húrin I",
    "Húrin II",
    "Húrin the Tall",
    "Húrin",
    "Hador (Steward)",
    "Hador",
    "Halbarad",
    "Haldad",
    "Haldan",
    "Haldar",
    "Haldir (First Age)",
    "Haldir of Lórien",
    "Haleth",
    "Hallas",
    "Halmir",
    "Hamfast Gamgee",
    "Handir",
    "Hardang",
    "Hareth",
    "Helm Hammerhand",
    "Herion",
    "Herucalmo",
    "Herumor",
    "Hirgon",
    "Hiril (House of Bëor)",
    "Hiril (House of Haleth)",
    "Huan",
    "Hundar",
    "Huor",
    "Hyarmendacil I",
    "Hyarmendacil II",
    "Ibûn",
    "Idril",
    "Ilúvatar",
    "Ilmarë",
    "Imbar",
    "Imin",
    "Iminyë",
    "Imrahil",
    "Indis",
    "Inglor",
    "Ingwë",
    "Inzilbêth",
    "Irimë",
    "Irmo",
    "Isildur",
    "Isilmë",
    "Isilmo",
    "Isumbras Took",
    "Ivriniel",
    "Kíli",
    "Khîm",
    "Khamûl",
    "Kings of Arnor",
    "Kings of Arthedain",
    "Kings of Gondor",
    "Léod",
    "Lúthien",
    "Lagduf",
    "Lalaith",
    "Legolas",
    "Lenwë",
    "Lindir",
    "Lobelia Sackville-Baggins",
    "Lotho Sackville-Baggins",
    "Lugdush",
    "Lurtz",
    "Míriel Ar-Zimraphel",
    "Míriel Serindë",
    "Mîm",
    "Mablung",
    "Maedhros",
    "Maeglin",
    "Maglor",
    "Magor",
    "Mahtan",
    "Maiar",
    "Malach",
    "Malbeth the Seer",
    "Mallor",
    "Malvegil",
    "Man in the Moon",
    "Manthor",
    "Manwë",
    "Marach",
    "Mardil Voronwë",
    "Mauhúr",
    "Meleth",
    "Melian",
    "Meneldil",
    "Meriadoc Brandybuck",
    "Minalcar",
    "Minardil",
    "Mithrandir",
    "Morgoth",
    "Morwen Steelsheen",
    "Morwen",
    "Mouth of Sauron",
    "Muzgash",
    "Náin I",
    "Náin II",
    "Náin",
    "Námo",
    "Níniel",
    "Nóm",
    "Nahar",
    "Narmacil I",
    "Narmacil II",
    "Narvi",
    "Nerdanel",
    "Nessa",
    "Nienna",
    "Nienor",
    "Nimloth",
    "Nimrodel",
    "Nori",
    "Ohtar",
    "Olórin",
    "Old Man Willow",
    "Olwë",
    "Ondoher",
    "Ori",
    "Ornendil",
    "Orodreth (Steward)",
    "Orodreth",
    "Oromë",
    "Oropher",
    "Orophin",
    "Ossë",
    "Ostoher",
    "Paladin II Took",
    "Paladin Took",
    "Pallando",
    "Pearl Took",
    "Pelendur",
    "Pengolodh",
    "Peregrin Took",
    "Pervinca Took",
    "Pimpernel Took",
    "Primula Brandybuck",
    "Princes of Dol Amroth",
    "Quickbeam Queen Berúthiel",
    "Rían",
    "Rómendacil I",
    "Rómendacil II",
    "Rúmil",
    "Radagast",
    "Rosie Cotton",
    "Sador",
    "Saeros",
    "Salgant",
    "Salmar",
    "Samwise Gamgee",
    "Saruman",
    "Sauron",
    "Scatha",
    "Shadowfax",
    "Shagrat",
    "Shelob",
    "Silmariën",
    "Singollo",
    "Siriondil",
    "Sméagol",
    "Smaug",
    "Snowmane",
    "son of Glóin Óin",
    "son of Gróin Óin",
    "Soronto",
    "Stewards of Gondor",
    "Strider",
    "Túrin I",
    "Túrin II",
    "Túrin",
    "Tal-Elmar",
    "Tar Alcarin",
    "Tar Aldarion",
    "Tar Amandil",
    "Tar Anárion",
    "Tar Ancalimë",
    "Tar Ancalimon",
    "Tar Anducal",
    "Tar Ardamin",
    "Tar Atanamir",
    "Tar Calion",
    "Tar Calmacil",
    "Tar Ciryatan",
    "Tar Elendil",
    "Tar Falassion",
    "Tar Herunúmen",
    "Tar Hostamir",
    "Tar Meneldur",
    "Tar Minastir",
    "Tar Minyatur",
    "Tar Palantir",
    "Tar Telemmaitë",
    "Tar Telemnar",
    "Tar Telperiën",
    "Tar Vanimeldë",
    "Tar- Súrion",
    "Tarannon Falastur",
    "Tarcil",
    "Tarondor of Arnor",
    "Tarondor of Gondor",
    "Tata",
    "Tatië",
    "Telchar",
    "Telemnar",
    "Telumehtar",
    "Théoden",
    "Théodred",
    "Théodwyn",
    "Thengel",
    "Thingol",
    "Thorin I",
    "Thorin II Oakenshield",
    "Thorin III Stonehelm",
    "Thorondir",
    "Thorondor",
    "Thráin I",
    "Thráin II",
    "Thrór",
    "Thranduil",
    "Tilion",
    "Tinúviel",
    "Tindomiel",
    "Tom (Troll)",
    "Tom Bombadil",
    "Treebeard",
    "Trotter",
    "Tulkas",
    "Tuor",
    "Turambar",
    "Turgon (Steward)",
    "Turgon",
    "Ufthak",
    "Uglúk",
    "Uinen",
    "Uldor",
    "Ulfang",
    "Ulfast",
    "Ulmo",
    "Ulwarth",
    "Umbardacil",
    "Undómiel",
    "Ungoliant",
    "Uolë Kúvion",
    "Urwen",
    "Vána",
    "Vairë",
    "Valacar",
    "Valandil of Andúnië",
    "Valandil of Arnor",
    "Valandur",
    "Varda",
    "Vardamir Nólimon",
    "Vidugavia",
    "Vidumavi",
    "Vinyarion",
    "Vorondil the Hunter",
    "Voronwë",
    "Walda",
    "Watcher in the Water",
    "Will Whitfoot",
    "William",
    "Witch-king of Angmar",
    "Wormtongue",
    "Wulf",
    "Yavanna",
    "Yávien"
  ]


var drugs = [
    "Abacavir Sulfate",
    "Abatacept",
    "Abilify",
    "Acamprosate Calcium",
    "Accretropin",
    "Aceon",
    "Aci-Jel",
    "Acthrel",
    "Actimmune",
    "Actisite",
    "Acular",
    "Acular LS",
    "Acuvail",
    "Adagen",
    "Adapalene",
    "Adcirca",
    "Adefovir Dipivoxil",
    "Adenoscan",
    "Adenosine",
    "Adipex-P",
    "AdreView",
    "Advair HFA",
    "Aerospan HFA",
    "Agalsidase Beta",
    "Aggrenox",
    "Akineton",
    "Alamast",
    "Albenza",
    "Aldactazide",
    "Aldactone",
    "Aldoril",
    "Aldurazyme",
    "Alemtuzumab",
    "Alglucosidase Alfa",
    "Allegra-D",
    "Allegra D 24 Hour",
    "Alli",
    "Aloprim",
    "Alora",
    "Alphanate",
    "Altace",
    "Altocor",
    "Altoprev",
    "Alupent",
    "Amantadine Hydrochloride",
    "Amerge",
    "Amifostine",
    "Amiloride",
    "Aminosalicylic Acid",
    "Aminosyn II 8.5%",
    "Amlodipine Besylate",
    "Amoxapine",
    "Amytal Sodium",
    "Anabolic steroids",
    "Anadrol-50",
    "Antithrombin",
    "Antivenin",
    "Antivert",
    "Aredia",
    "Aricept",
    "Armodafinil",
    "Arranon",
    "Artane",
    "Asclera",
    "Ascorbic Acid",
    "Astemizole",
    "Atacand",
    "Atacand HCT",
    "Atazanavir Sulfate",
    "Atomoxetine HCl",
    "Atridox",
    "Atripla",
    "Atropen",
    "Augmentin XR",
    "Avage",
    "Avandia",
    "Avastin",
    "Avinza",
    "Axid",
    "Azasan",
    "Azasite",
    "Azelaic Acid",
    "Azelastine Hydrochloride",
    "Azilect",
    "Azmacort",
    "Balsalazide",
    "Benazepril",
    "Benzocaine",
    "Benzoyl Peroxide Gel",
    "Benzphetamine",
    "Benztropine Mesylate",
    "Bepreve",
    "Betagan",
    "Bethanechol",
    "Betimol",
    "Betoptic S",
    "Bevacizumab",
    "BiCNU",
    "Biperiden",
    "Bismuth Subcitrate Potassium",
    "Bismuth Subsalicylate",
    "Blocadren",
    "Boniva",
    "Bontril",
    "Boostrix",
    "Botulinum Toxin Type A",
    "Bravelle",
    "Brevibloc",
    "Bromocriptine Mesylate",
    "Brovana",
    "Budesonide",
    "Buprenorphine",
    "Buspar",
    "Buspirone",
    "Busulfan",
    "Busulfex",
    "Cabergoline",
    "Caduet",
    "Calcitonin-Salmon",
    "Calcium Chloride",
    "Calcium Disodium Versenate",
    "Calcium Gluconate",
    "Campral",
    "Canasa",
    "Cancidas",
    "Captopril",
    "Carac",
    "Carbatrol",
    "Cardiolite",
    "Carisoprodol",
    "Carmustine",
    "Carvedilol",
    "Casodex",
    "Caspofungin Acetate",
    "Cataflam",
    "Catapres",
    "Catapres-TTS",
    "Caverject",
    "Cedax",
    "Cefditoren Pivoxil",
    "Cefixime",
    "Cefizox",
    "Cefotetan",
    "Ceftazidime",
    "Ceftibuten",
    "Ceftin",
    "Cefzil",
    "Celestone Soluspan",
    "Celexa",
    "CellCept",
    "Cellulose",
    "Celontin",
    "Cephalexin",
    "Cerebyx",
    "Ceretec",
    "Cerubidine",
    "Cerumenex",
    "Cervidil",
    "Cetirizine",
    "Cetraxal",
    "Cetrotide",
    "Cetuximab",
    "Chantix",
    "Chibroxin",
    "Chlorambucil",
    "Chloramphenicol Sodium Succinate",
    "Chloroprocaine",
    "Chlorpheniramine Maleate",
    "Chlorpromazine",
    "Chlorpropamide",
    "Chlorthalidone",
    "Cholera Vaccine",
    "Chorionic Gonadotropin",
    "Ciclopirox Gel",
    "Cilostazol",
    "Cinobac",
    "Cipro",
    "Cipro XR",
    "Cisapride",
    "Clarinex",
    "Clarithromycin",
    "Claritin",
    "Cleocin",
    "Cleviprex",
    "Climara Pro",
    "Clinoril",
    "Clobetasol Propionate",
    "Clocortolone",
    "Clofarabine",
    "Clonidine",
    "Clorazepate Dipotassium",
    "Clorpres",
    "Clotrimazole",
    "Cocaine",
    "Codeine",
    "Cognex",
    "Colazal",
    "Colchicine",
    "Colcrys",
    "Colesevelam Hcl",
    "Combivir",
    "Conjugated Estrogens",
    "Copaxone",
    "Corgard",
    "Cosmegen",
    "Coumadin",
    "Crolom",
    "Cromolyn Sodium",
    "Cubicin",
    "Curosurf",
    "Cuvposa",
    "Cyanocobalamin",
    "Cyclobenzaprine Hcl",
    "Cyclophosphamide",
    "Cyclosporine",
    "Cylert",
    "Cymbalta",
    "Cyproheptadine",
    "Cystadane",
    "Cytogam",
    "Cytomel",
    "Dacarbazine",
    "Daraprim",
    "Darvocet-N",
    "Darvon Compound",
    "Dasatinib",
    "Daunorubicin",
    "Daypro",
    "Daypro Alta",
    "DDAVP Nasal Spray",
    "Demadex",
    "Demeclocycline HCl",
    "Demser",
    "Depacon",
    "DepoDur",
    "Desferal",
    "Desogen",
    "Desonate",
    "DesOwen",
    "Detrol",
    "Detrol LA",
    "Dexlansoprazole",
    "Dexmethylphenidate Hydrochloride",
    "Dexrazoxane",
    "Diamox Sequels",
    "Dicyclomine",
    "Didanosine",
    "Diethylpropion",
    "Differin",
    "Diflucan",
    "Digoxin Immune Fab",
    "Diovan HCT",
    "Diphenhydramine",
    "Diphtheria-Tetanus Vaccine",
    "Diprolene AF",
    "Dipyridamole",
    "Ditropan",
    "Dobutamine",
    "Dofetilide",
    "Dolophine",
    "Donepezil Hydrochloride",
    "Dopamine Hydrochloride",
    "Dopar",
    "Dopram",
    "Doral",
    "Doryx",
    "Dorzolamide",
    "Dovonex",
    "Doxacurium Chloride",
    "Doxapram",
    "Doxazosin Mesylate",
    "Doxepin",
    "Doxercalciferol",
    "Doxil",
    "Doxycycline",
    "Doxycycline Hyclate",
    "Drisdol",
    "Dronabinol",
    "Drospirenone and Estradiol",
    "Duetact",
    "Duraclon",
    "Dynacirc",
    "Dynacirc CR",
    "Dynapen",
    "Dyphylline",
    "Econazole Nitrate",
    "Edrophonium",
    "Efavirenz",
    "Elaprase",
    "Elavil",
    "Eletriptan hydrobromide",
    "Eligard",
    "Ellence",
    "Elmiron",
    "Elspar",
    "Emadine",
    "Emcyt",
    "Emedastine",
    "Empirin",
    "Emsam",
    "Emtricitabine",
    "Emtriva",
    "Endocet",
    "Endometrin",
    "Enflurane",
    "Engerix-B",
    "Entereg",
    "Eovist",
    "Epinephrine",
    "Epipen",
    "Epirubicin hydrochloride",
    "Epivir",
    "Equetro",
    "Eraxis",
    "Erbitux",
    "Ergocalciferol",
    "Erlotinib",
    "Erythrocin Stearate",
    "Esomeprazole Sodium",
    "Essential Amino Acids",
    "Estrace",
    "Estradiol",
    "Estradiol Acetate",
    "Estradiol valerate",
    "Estratest",
    "Estropipate",
    "Eszopiclone",
    "Etanercept",
    "Ethacrynic Acid",
    "Ethambutol",
    "Ethinyl Estradiol",
    "Ethiodol",
    "Ethosuximide",
    "Etidocaine HCl",
    "Etidronate Disodium",
    "Etopophos",
    "Etrafon",
    "Eulexin",
    "Evista",
    "Evoxac",
    "Exelderm",
    "Exjade",
    "Extavia",
    "Factor IX Complex",
    "Factrel",
    "Famciclovir",
    "Famotidine Injection",
    "Famvir",
    "Fansidar",
    "Febuxostat",
    "Feridex I.V.",
    "Fesoterodine Fumarate Extended",
    "Finacea",
    "Flector",
    "Flonase",
    "Florinef",
    "Floxuridine",
    "Fluconazole",
    "Flucytosine",
    "Fludara",
    "Fludarabine Phosphate",
    "Fludrocortisone",
    "Flumazenil",
    "FluMist",
    "Fluocinolone Acetonide",
    "Fluoroplex",
    "Fluorouracil",
    "Fluoxetine Hydrochloride",
    "Flurbiprofen",
    "Fluress",
    "Fluticasone Propionate",
    "Fluvirin",
    "FML",
    "Folic Acid",
    "Follitropin Alfa",
    "Follitropin Beta",
    "Fomepizole",
    "Foradil Aerolizer",
    "Foradil Certihaler",
    "Forane",
    "Fosamax Plus D",
    "Fosamprenavir Calcium",
    "Foscavir",
    "Fosphenytoin Sodium",
    "Fragmin",
    "Frovatriptan Succinate",
    "Fulvestrant",
    "Fungizone",
    "Furadantin",
    "Furosemide",
    "Furoxone",
    "Fuzeon",
    "Gabitril",
    "Gadobenate Dimeglumine",
    "Gadofosveset Trisodium",
    "Galsulfase",
    "Gamunex",
    "Geocillin",
    "Geodon",
    "Gleevec",
    "Glucophage XR",
    "Glucovance",
    "Glyburide",
    "Glycopyrrolate",
    "Glynase",
    "Glyset",
    "Gold Sodium Thiomalate",
    "Gonadorelin",
    "Gonal-F",
    "Gonal-f RFF",
    "Grifulvin V",
    "Griseofulvin",
    "Guanethidine Monosulfate",
    "Gynazole",
    "Haemophilus b Conjugate Vaccine",
    "Halcinonide",
    "Haldol",
    "Halobetasol Propionate",
    "Haloperidol",
    "Healon",
    "HepaGam B",
    "Heparin Lock Flush",
    "HepatAmine",
    "Hepatitis A Vaccine, Inactivated",
    "Hepatitis B Immune Globulin",
    "Hepflush-10",
    "Herceptin",
    "Hexachlorophene",
    "HibTITER",
    "Hivid",
    "Human Secretin",
    "Humira",
    "Humulin N",
    "Hyalgan",
    "Hydrocodone Bitartrate and Acetaminophen",
    "Hydroxyethyl Starch",
    "Hylenex",
    "Hyoscyamine",
    "Hytrin",
    "Ibuprofen Lysine",
    "Idamycin",
    "Idamycin PFS",
    "Ifosfamide",
    "Iloperidone",
    "Imipramine",
    "Imiquimod",
    "Imitrex",
    "Immune Globulin",
    "Immune Globulin Intravenous",
    "Implanon",
    "Inderal LA",
    "Indigo Carmine",
    "InnoPran XL",
    "Insulin",
    "Insulin Aspart",
    "Intelence",
    "Intralipid 20%",
    "Intuniv",
    "Invanz",
    "Invega",
    "Inversine",
    "Ionamin",
    "Irinotecan Hydrochloride",
    "Isentress",
    "Ismo",
    "Isocarboxazid",
    "Isoptin SR",
    "Isopto Carpine",
    "Isopto Hyoscine",
    "Istalol",
    "Isuprel",
    "Ixempra",
    "Jalyn",
    "Janumet",
    "Je-Vax",
    "K-LOR",
    "Kaletra",
    "Kariva",
    "Kenalog",
    "Kinlytic",
    "Klonopin",
    "Kuvan",
    "Kytril",
    "Labetalol",
    "lacosamide",
    "Lamisil",
    "Lamivudine / Zidovudine",
    "Latanoprost",
    "Letairis",
    "Letrozole",
    "Leuprolide Acetate",
    "Leustatin",
    "Levalbuterol",
    "Levaquin",
    "Levemir",
    "Levo-T",
    "Levocabastine",
    "Levofloxacin",
    "Levonorgestrel",
    "Levonorgestrel and Ethinyl Estradiol",
    "Levonorgestrel Implants",
    "Levonorgestrel, Ethinyl Estradiol",
    "Lexapro",
    "Lexiscan",
    "Lexxel",
    "Librium",
    "Lidex",
    "Lidoderm",
    "Linezolid",
    "Lipofen",
    "Liposyn II",
    "Liraglutide",
    "Lisinopril and Hydrochlorothiazide",
    "Locoid",
    "Lodine",
    "Loperamide Hcl",
    "Lopid",
    "Loprox Gel",
    "Loracarbef",
    "Lortab",
    "Lotemax",
    "Lotensin",
    "Lotronex",
    "Lovenox",
    "Loxapine",
    "Loxitane",
    "Lucentis",
    "Luvox CR",
    "Lybrel",
    "M-M-R",
    "Malarone",
    "Malathion",
    "Mandol",
    "Mangafodipir",
    "Maraviroc",
    "Marinol",
    "Maxitrol",
    "Mecasermin",
    "Meclofenamate",
    "Mefloquine",
    "Melphalan",
    "Menactra",
    "Menest",
    "Menotropins",
    "Mephobarbital",
    "Mequinol and Tretinoin",
    "Meropenem",
    "Merrem I.V.",
    "Mesalamine",
    "Mesna",
    "Mestinon",
    "Metadate ER",
    "Metaglip",
    "Metaproterenol Sulfate",
    "Metaxalone",
    "Metformin Hcl",
    "Methadone Hydrochloride",
    "Methadose Oral Concentrate",
    "Methazolamide",
    "Methenamine Hippurate",
    "Methergine",
    "Methohexital Sodium",
    "Methyclothiazide",
    "Methyldopa",
    "Methylene Blue",
    "Methylergonovine Maleate",
    "Methylin",
    "Methyltestosterone",
    "Metipranolol",
    "Metoclopramide",
    "Metoprolol Tartrate",
    "MetroLotion",
    "Metyrapone",
    "Metyrosine",
    "Miacalcin",
    "Micro-K",
    "Micronase",
    "Micronized Glyburide",
    "Midazolam",
    "Midodrine Hydrochloride",
    "Milrinone",
    "Minocin",
    "Minocycline",
    "Minoxidil",
    "Miochol-E",
    "Miostat",
    "Mitomycin",
    "Mobic",
    "Modafinil",
    "Monistat",
    "Monistat-Derm",
    "Morrhuate Sodium",
    "Motrin",
    "Moxatag",
    "Mozobil",
    "Multaq",
    "Multi Vitamin",
    "Multihance",
    "Mustargen",
    "Mutamycin",
    "Myambutol",
    "Mycamine",
    "Mycelex",
    "Mycophenolic Acid",
    "Myfortic",
    "Mykrox",
    "Myobloc",
    "Myochrysine",
    "Nafcillin Sodium",
    "Naftifine Hcl",
    "Nalmefene Hydrochloride",
    "Naltrexone",
    "Naproxen",
    "Nascobal",
    "Natazia",
    "Natrecor",
    "Navelbine",
    "Nebcin",
    "Nebivolol Tablets",
    "Nedocromil",
    "Nelarabine",
    "Nelfinavir Mesylate",
    "NeoProfen",
    "Neostigmine",
    "Nephramine",
    "Nesacaine",
    "Neulasta",
    "Nexavar",
    "Niaspan",
    "Nicotrol",
    "Nicotrol NS",
    "Nilandron",
    "Nilotinib Capsules",
    "Nimbex",
    "Nimotop",
    "Nitroglycerin",
    "NitroMist",
    "Nizatidine",
    "Nizoral",
    "Noctec",
    "Nor-QD",
    "Norethindrone and Ethinyl Estradiol",
    "Noritate",
    "Nortriptyline Hydrochloride",
    "Norvasc",
    "NovoLog Mix 70/30",
    "Novoseven",
    "Numorphan",
    "Nutropin AQ",
    "Nutropin Depot",
    "Nydrazid",
    "Omeprazole",
    "Omnaris",
    "Opana",
    "Opticrom",
    "OptiMARK",
    "Optipranolol",
    "Oracea",
    "Oraqix",
    "Orfadin",
    "Orlaam",
    "Orlistat",
    "Orudis",
    "Ovcon",
    "Ovide",
    "Oxandrolone",
    "Oxaprozin",
    "Oxistat",
    "Oxsoralen-Ultra",
    "Oxycodone HCl",
    "Oxycodone Hydrochloride",
    "Oxycontin",
    "Oxymetholone",
    "Oxymorphone",
    "Oxytetracycline",
    "Paclitaxel",
    "Palifermin",
    "Paliperidone",
    "Palonosetron hydrochloride",
    "Panhematin",
    "Pantoprazole",
    "Parafon Forte",
    "Parnate",
    "Paser",
    "Pataday",
    "Pazopanib",
    "Pediapred",
    "PEG 3350",
    "Pegfilgrastim",
    "Pemirolast Potassium",
    "Penciclovir",
    "Penicillamine",
    "Penlac",
    "Pentetate Zinc Trisodium",
    "Pentobarbital",
    "Pentoxifylline",
    "Perflutren",
    "Perindopril Erbumine",
    "Permax",
    "Persantine",
    "Pfizerpen",
    "Phenazopyridine",
    "Phenelzine",
    "Phenobarbital",
    "Phenoxybenzamine",
    "Phenylephrine HCl",
    "Phenylephrine Hydrochloride",
    "Phenytoin",
    "Phosphate",
    "Photofrin",
    "Pilocarpine Hydrochloride",
    "Pilopine HS",
    "Pindolol",
    "Pipracil",
    "Piroxicam",
    "Plaquenil",
    "PlasmaLyte A",
    "Plavix",
    "Plenaxis",
    "Pletal",
    "Pneumovax",
    "Podophyllin",
    "Polidocanol",
    "Polyethylene Glycol 3350",
    "Polythiazide",
    "Pramipexole",
    "Pred-G",
    "Prednicarbate",
    "Prednisolone Acetate",
    "Prednisone",
    "Prefest",
    "Pregnyl",
    "Premarin",
    "Prepidil",
    "Prevpac",
    "Priftin",
    "Primacor",
    "Primaquine",
    "Primidone",
    "Prinivil",
    "Prinzide",
    "Pristiq",
    "Procainamide",
    "Procalamine",
    "Prochlorperazine Maleate",
    "ProHance",
    "Proleukin",
    "Prolixin",
    "Promethazine HCl",
    "Promethazine Hydrochloride",
    "Prometrium",
    "Propecia",
    "Proquin XR",
    "Prostin VR Pediatric",
    "Protein C Concentrate",
    "Protopic",
    "Protriptyline Hydrochloride",
    "Proventil HFA",
    "Provisc",
    "Provocholine",
    "Pulmicort Flexhaler",
    "Pylera",
    "Pyrazinamide",
    "Pyridium",
    "Pyridostigmine",
    "Qualaquin",
    "Quazepam",
    "Quinidine Sulfate",
    "Quixin",
    "Rabies Vaccine",
    "Raltegravir",
    "Ranexa",
    "Ranitidine Hcl",
    "Rapamune",
    "Rasagiline",
    "Raxar",
    "Rebetol",
    "Remicade",
    "Remifentanil",
    "Renese",
    "ReoPro",
    "Rescriptor",
    "Rescula",
    "Revatio",
    "Revex",
    "Revia",
    "Reyataz",
    "Rezulin",
    "Rhinocort Aqua",
    "Rhogam Ultra-Filtered Plus",
    "RiaSTAP",
    "Rifamate",
    "Riomet",
    "Risperidone",
    "Ritalin",
    "Rituximab",
    "Rivastigmine Tartrate",
    "Robinul",
    "Rosiglitazone Maleate",
    "Rotarix",
    "RotaTeq",
    "Roxicet",
    "Roxicodone",
    "Ryzolt",
    "Sabril",
    "Sacrosidase",
    "Samsca",
    "Sanctura",
    "Santyl",
    "Saphris",
    "Scopolamine",
    "Seasonale",
    "Selegiline Hydrochloride",
    "Selsun",
    "Septra",
    "Serax",
    "Sertraline Hcl",
    "Serzone",
    "Sevoflurane",
    "Sibutramine Hydrochloride Monohydrate",
    "Silenor",
    "Simponi",
    "Sirolimus",
    "Sitagliptin Metformin HCL",
    "Slow-K",
    "Sodium Bicarbonate",
    "Sodium ferric gluconate",
    "Sodium Iodide I 131",
    "Sodium Polystyrene Sulfonate",
    "Sodium Sulfacetamide",
    "Soma Compound",
    "Somatrem",
    "Somatropin",
    "Sonata",
    "Soriatane",
    "Sotradecol",
    "Spiriva",
    "Sporanox",
    "Sprix",
    "Sprycel",
    "Stalevo",
    "Starlix",
    "Stavudine",
    "Streptokinase",
    "Strontium-89",
    "Suboxone",
    "Succimer",
    "Succinylcholine Chloride",
    "Sucralfate",
    "Sulfamylon",
    "Sunitinib Malate",
    "Sutent",
    "Synthroid",
    "Synvisc",
    "Syprine",
    "Tacrolimus",
    "Talacen",
    "Talwin Nx",
    "Tamiflu",
    "Tamoxifen Citrate",
    "Tapazole",
    "Targretin",
    "Tasmar",
    "Tegretol",
    "Tekturna HCT",
    "Telavancin",
    "Telbivudine",
    "Telmisartan",
    "Temovate Scalp",
    "Temozolomide",
    "Temsirolimus",
    "Teniposide",
    "Terazol 3, Terazol 7",
    "Tessalon",
    "Testolactone",
    "Testred",
    "Teveten HCT",
    "Theracys",
    "Thiabendazole",
    "Thiethylperazine",
    "Thiopental Sodium",
    "Thioridazine",
    "Thiothixene Hcl",
    "Thrombin",
    "Thyrolar",
    "Thyrotropin Alfa",
    "Tiazac",
    "Ticarcillin",
    "Tinzaparin",
    "Tirosint",
    "Tizanidine",
    "Tobrex",
    "Tofranil-PM",
    "Tolazamide",
    "Tolmetin Sodium",
    "Tonocard",
    "Topicort",
    "Topiramate",
    "Topotecan Hydrochloride",
    "Toradol",
    "Torsemide",
    "Toviaz",
    "Tramadol Hcl",
    "Tranxene",
    "Trastuzumab",
    "Trasylol",
    "Tretinoin",
    "Trexall",
    "Tri-Sprintec",
    "Triamcinolone Acetonide",
    "Triazolam",
    "Tribenzor",
    "Trientine",
    "Trihexyphenidyl",
    "Trilipix",
    "Trilisate",
    "Trimethadione",
    "Trimethoprim",
    "Trimethoprim and Sulfamethoxazole",
    "Trimetrexate Glucuronate",
    "Trizivir",
    "Trovafloxacin",
    "Trovan",
    "Trusopt",
    "Trypan Blue",
    "Tussionex",
    "Tysabri",
    "Tyvaso",
    "Uloric",
    "Ultiva",
    "Ultram",
    "Ultrase",
    "Ultravate",
    "Unasyn",
    "Urex",
    "Ursodiol",
    "Vagistat-1",
    "Valacyclovir Hydrochloride",
    "Valganciclovir Hcl",
    "Valium",
    "Valproic Acid",
    "Valsartan and Hydrochlorothiazide",
    "Vancomycin Hydrochloride",
    "Vaprisol",
    "Vasocidin",
    "Vasotec",
    "Vasovist",
    "Vectibix",
    "Vectical",
    "Velosulin",
    "Veltin",
    "Venlafaxine Hydrochloride",
    "Veramyst",
    "Vermox",
    "Vesanoid",
    "VESIcare",
    "Vibramycin",
    "Vicodin",
    "Vicodin HP",
    "Vicoprofen",
    "Victoza",
    "Vimovo",
    "Vimpat",
    "Vinblastine Sulfate",
    "Viokase",
    "Vioxx",
    "Viread",
    "VisionBlue",
    "Vistide",
    "Vitamin K1",
    "Vivactil",
    "Vivelle-Dot",
    "Vusion",
    "Vytorin",
    "Winstrol",
    "Xigris",
    "Xolair",
    "Yellow Fever Vaccine",
    "Zaditor",
    "Zalcitabine",
    "Zanosar",
    "Zelnorm",
    "Zemaira",
    "Zemplar",
    "Zestoretic",
    "Zestril",
    "Ziconotide",
    "Zingo",
    "Zmax",
    "Zocor",
    "Zolinza",
    "Zolmitriptan",
    "Zonalon",
    "Zoster Vaccine Live",
    "Zosyn",
    "Zyclara",
    "Zyflo",
    "Zylet",
    "Zyloprim",
    "Zymaxid"
  ]






b.textFont ("Favorit", "Bold");
b.textSize (40);
b.text (
  "Whenever " +
  honorifics[b.floor (b.random (honorifics.length))] +
  " " +
  famousPeople[b.floor(b.random (famousPeople.length))] +
  " furiously licked " +
  tolkienCharacter[b.floor (b.random (tolkienCharacter.length))] +
  "’s " +
  bodyParts[b.floor(b.random (bodyParts.length))] +
  " the price of " +
  drugs[b.floor(b.random (drugs.length))] +
  " dropped rapidly."
  , 10, 50, b.width-20, 100);

b.textSize (20);
b.textFont ("Favorit")
b.textAlign (Justification.LEFT_ALIGN );




}

b.go();
